# this is not the best python scripting practice, but if you want everything in one big list
from rhinoscript.userinterface import *
from rhinoscript.dimension import *
from rhinoscript.pointvector import *
from rhinoscript.line import *
from rhinoscript.utility import *
from rhinoscript.document import *
from rhinoscript.hatch import *
from rhinoscript.transformation import *
from rhinoscript.application import *
from rhinoscript.light import *
from rhinoscript.grips import *
from rhinoscript.object import *
from rhinoscript.mesh import *
from rhinoscript.group import *
from rhinoscript.selection import *
from rhinoscript.plane import *
from rhinoscript.material import *
from rhinoscript.userdata import *
from rhinoscript.geometry import *
from rhinoscript.block import *
from rhinoscript.curve import *
from rhinoscript.linetype import *
from rhinoscript.view import *
from rhinoscript.surface import *
from rhinoscript.layer import *
